export const assets: any = {
    logo: require('./logo/logo.png'),
    logoImage: require('./logo/logoImage.png'),
    faviconLogo: require('./logo/faviconLogo.png'),
    background: require('./images/background.png'),
    // homepage
    banner: require('./images/Banner.png'),
    image1: require('./images/homepage/Image1.png'),
    image2: require('./images/homepage/Image2.png'),
    image3: require('./images/homepage/Image3.png'),
    image4: require('./images/homepage/Image4.png'),
    image5: require('./images/homepage/Image5.png'),
    image6: require('./images/homepage/Image6.png'),
    image7: require('./images/homepage/Image7.png'),
    image8: require('./images/homepage/Image8.png'),
    image9: require('./images/homepage/Image9.png'),
    image10: require('./images/homepage/Image10.png'),
    image11: require('./images/homepage/Image11.png'),
    image12: require('./images/homepage/Image12.png'),
    image13: require('./images/homepage/Image13.png'),
    image14: require('./images/homepage/Image14.png'),
    image15: require('./images/homepage/Image15.png'),
    image16: require('./images/homepage/Image16.png'),
    bedroom: require('./images/homepage/Bedroom.png'),
    dining: require('./images/homepage/Dining.png'),
    living: require('./images/homepage/Living.png'),
    syltherine: require('./images/homepage/Syltherine.png'),
    //profile
    avatar: require('./images/avatar.jpg'),
    // footer
    freeShipping: require('./images/footer/FreeShipping.png'),
    highQuality: require('./images/footer/HighQuality.png'),
    support: require('./images/footer/Support.png'),
    warrantyProtection: require('./images/footer/WarrantyProtection.png'),
};
