export const assets: any = {
    logo: require('./logo/logo.png'),
    loginLogo: require('./logo/loginLogo.png'),
    faviconLogo: require('./logo/faviconLogo.png'),
    facebookLogo: require('./logo/facebookLogo.png'),
    googleLogo: require('./logo/googleLogo.png'),
    decorImg: require('./logo/decorLogin.jpg'),
    chairImg: require('./logo/chair.png'),
    signUpBG: require('./images/signUpBG.jpg'),
    signUpBG2: require('./images/signUpBG2.jpg'),
    signUpBG3: require('./images/signUpBG3.jpg'),
    signUpBG4: require('./images/signUpBG4.jpg'),
    signUpBG6: require('./images/signUpBG6.jpg'),
    signInBG: require('./images/signInBG.jpg'),
    signInBG2: require('./images/signInBG2.jpg'),
    signInBG3: require('./images/signInBG3.jpg'),
};
